### ISSUE TITLE
help

### ISSUE THREAD

**Issue by perish6368** [iraizo/sharex-uploader#4]
PDO Error: SQLSTATE[HY000] [1045] Access denied for user 'user'@'localhost' (using password: YES)

**Comment by iraizo** [comment]
The user does not have access to the database

**Comment by perish6368** [comment]
wdym i put in the right login details

**Comment by perish6368** [comment]
lacking#2832 can you add me on discord pls

**Comment by iraizo** [comment]
No i can't all support goes over github issues.

**Comment by iraizo** [comment]
> wdym i put in the right login details

That does not mean the user has permission to it
